BUGFIX: Getting 404 uriSegment for default dimensions if no dimension…
mocdk/MOC.NotFound pull request #10
Opened 2016-10-27 14:41 UTC by peterbucher

…s are explicitly given and supportEmptySegmentsForDimensions is set to false

This fixes that MOC.NotFound works as expected if "supportEmptySegmentsForDimensions" is set to false.
We - and i think this is not uncommon - have to set the setting above to false, because we have the case of non-unique dimension values. E.g. country=de and language=de which then is "de_de".

But when this setting is set to "false", MOC.NotFound does not show the error page of the default dimension, but the ugly exception which says:

This only happen when the website is requested with no dimension values, e.g. "http://site.dev/".

`Exception #1426446160: Uri with path "http://site.dev/404" could not be found.

14 MOC\NotFound\ViewHelpers\RequestViewHelper_Original::render("404")
13 call_user_func_array(array|2|, array|1|)
12 TYPO3\Fluid\Core\ViewHelper\AbstractViewHelper::callRenderMethod()
11 TYPO3\Fluid\Core\ViewHelper\AbstractViewHelper::initializeArgumentsAndRender()
10 FluidCache_Standalone_template_file_404_2cfc2abbfbe744b0776da72acd2cde34a527c753::{closure}()
9 TYPO3\Fluid\Core\ViewHelper\AbstractViewHelper::renderChildren()
8 TYPO3\Fluid\ViewHelpers\Format\RawViewHelper_Original::render(NULL)
7 call_user_func_array(array|2|, array|1|)
6 TYPO3\Fluid\Core\ViewHelper\AbstractViewHelper::callRenderMethod()
5 TYPO3\Fluid\Core\ViewHelper\AbstractViewHelper::initializeArgumentsAndRender()
4 FluidCache_Standalone_template_file_404_2cfc2abbfbe744b0776da72acd2cde34a527c753::render(TYPO3\Fluid\Core\Rendering\RenderingContext)
3 TYPO3\Fluid\View\AbstractTemplateView::render()
2 TYPO3\Flow\Error\DebugExceptionHandler::echoExceptionWeb(TYPO3\Flow\Mvc\Controller\Exception\InvalidControllerException)
1 TYPO3\Flow\Error\AbstractExceptionHandler::handleException(TYPO3\Flow\Mvc\Controller\Exception\InvalidControllerException)`

With this fix then, the default dimension values will be put before the $path variable, the route is valid and the default 404 uriPathSegment will be displayed.

2016-11-01 09:21 UTC, kdambekalns approved these changes
To clear up (my) confusion: #8 described (and fixed it with #9) the problem for not existing documents _if dimensions where given_. This PR fixes the generation of a proper 404 result, in case _a path is given without dimensions_ (contrary to the PR description an empty path, i.e. `http://site.dev/`, works fine).

@peterbucher Could you please edit title and description to make this a bit clearer? Other than that, works as expected.

2016-11-02 12:11 UTC, peterbucher commented
@kdambekalns Thanks for your effort into this.

2017-01-26 18:14 UTC, aertmann requested changes
hey found a couple of issues with this approach

1. it uses the dimension values instead of the uri segments, which only works when those coincidentally happen to match
2. in case of the amount of dimension parts equals the amount of dimensions, this fix doesn't work

2017-01-26 18:18 UTC, aertmann approved these changes

2017-01-26 18:19 UTC, aertmann commented
Sorry for the delay, forgot about this issue.

Pushed a new fix which would work as far as I can tell, please have a look @peterbucher @kdambekalns

2017-05-02 09:51 UTC, gerhard-boden approved these changes
Just tested, this works! Thanks guys! 👍

2017-05-02 11:58 UTC, merged

2017-05-17 07:40 UTC, peterbucher commented
@aertmann I just tested version 3.0.1 and it works as expected! My initial issue is resolved now with this changes. 👍

2017-05-17 12:39 UTC, aertmann commented
@peterbucher: good to hear, thanks for checking in again